name: MOEX Scraper

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:       # кнопка ручного запуска в GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests gspread google-auth

      - name: Run scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python stock_scraper.py
